# Dokploy configuration for Medusa E-commerce

services:
  # Backend Medusa Configuration
  medusa-backend:
    build:
      context: ./medusa-store
      dockerfile: Dockerfile
    restart: always
    command: npx medusa develop --host 0.0.0.0
    environment:
      - NODE_ENV=development
      - PORT=9000
      - MEDUSA_HOST=0.0.0.0
      - DATABASE_URL=postgres://postgres:P0stgr3SQL@postgres:5432/medusa
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=shOJCFOdVXEjHBiVXaTKDPkA9Di/4fvUNayuIq9pA9U7H1ooLPLizaGHbYsKX67eOiK2HfSQzgAnoDC2Xnp7pw==
      - COOKIE_SECRET=r2dY7Lyp5WRDxi6MoaZffjZ8aQ7ifFJ3Ipzhh+lyocUh234XVLdCjCpzF5BgNJR5ECWMDCwvEk4X2/3k8twCTQ==
      - STORE_CORS=*
      - ADMIN_CORS=*
    ports:
      - "9000:9000"
    depends_on:
      - postgres
      - redis

  # Storefront Configuration
  medusa-storefront:
    build:
      context: ./medusa-storefront
      dockerfile: Dockerfile
    restart: always
    command: npm run dev
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_MEDUSA_BACKEND_URL=http://medusa-backend:9000
      - PORT=8000
    ports:
      - "8000:8000"
    depends_on:
      - medusa-backend

  # PostgreSQL database for Medusa
  postgres:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P0stgr3SQL
      - POSTGRES_DB=medusa
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching and queue management
  redis:
    image: redis:6
    restart: always
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
