version: "3"

services:
  # Backend Medusa Configuration
  medusa-backend:
    build:
      context: ./medusa-store
      dockerfile: Dockerfile
    restart: always
    command: npx medusa start
    environment:
      - NODE_ENV=production
      - PORT=9000
      - MEDUSA_HOST=0.0.0.0
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/medusa
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=supersecret
      - COOKIE_SECRET=supersecret
      - STORE_CORS=*
      - ADMIN_CORS=*

    ports:
      - "9000:9000"
    depends_on:
      - postgres
      - redis

  # Storefront Configuration
  medusa-storefront:
    build:
      context: ./medusa-storefront
      dockerfile: Dockerfile
    restart: always
    command: node .next/standalone/server.js
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_MEDUSA_BACKEND_URL=http://medusa-backend:9000
      - PORT=8000
    ports:
      - "8000:8000"
    depends_on:
      - medusa-backend

  # PostgreSQL database for Medusa
  postgres:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=medusa
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching and queue management
  redis:
    image: redis:6
    restart: always
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
